spring.application.name=NetworkPacketAnalyzer
server.port=8080
server.address=0.0.0.0
server.servlet.context-path=/
logging.level.root=WARN
logging.level.org.springframework.web=WARN
carlos.gemini.api-key=${GEMINI_API_KEY:}
